export { default as Home } from "./Home/Home"
export { default as ProductDetail } from "./ProductDetail/ProductDetail"
export { default as Contact } from "./Contact/Contact"
export { default as Shop } from "./Shop/Shop"
export { default as Cart } from "./Cart/Cart"
export { default as ShippingReturn } from "./ShippingReturn/ShippingReturn"
export { default as Checkout } from "./Checkout/Checkout"